### ISSUE TITLE
Add "Quit DisableMonitor" option

### ISSUE THREAD

**Issue by agsimeonov** [Eun/DisableMonitor#14]
It would be nice to have a built-in "Quit DisableMonitor" option in the dropdown Taskbar GUI, instead of having to run "kill DisableMonitor" in Terminal.

**Comment by Eun** [comment]
Hold the <kbd>⌥</kbd> key to make the Quit Option available

**Comment by williamboman** [comment]
@Euw Interesting, is this a common convention for OS X menu items (asking purely out of curiosity)?

**Comment by Eun** [comment]
In the next release the Quit option will always be visible!

**Comment by Razoxane** [comment]
:+1: for always visible.
