### ISSUE TITLE
Display does not get disabled. 

### ISSUE THREAD

**Issue by atanasbozhkov** [Eun/DisableMonitor#15]
I am unable to disable the internal display on my MBP.

**Setup:**
I have an external monitor attached through a DP cable to a rMBP Late 2013 running Yosemite 10.10.1  

**Steps to reproduce:**
After clicking "disable" the internal screen flashes black and then comes on again. I am then unable to move the mouse or any windows to it, but it still has a wallpaper and a menu bar on it. System preferences also shows that two displays are connected, even though the arrangements are all messed up.

**Comment by Eun** [comment]
Same as Issue #11
