### ISSUE TITLE
Both external and internal screens get disabled after display sleeps

### ISSUE THREAD

**Issue by Sahandyman** [Eun/DisableMonitor#29]
Hi Eun,
First, thank you for this amazing app. I'm running DM 1.9, on a 2012 retina display 13" running Maverick 10.9.5. Just wanted to let you know that when my computer goes to sleep both screens, main and the external monitor get disabled. By that, I mean both screens have power going thru them but will be black and won't display anything. However, everything else is still running in the background. I have tried many things to re-enable the main screen but to no avail. I have tried, unplugging the external monitor, closing the mac's lid, force closing the app, even made a workflow to try and re-enable to main screen using automator "watch me do" but none of them helped. The only thing that made a difference at this point was a restart. This has happened many times now. Please help, I'm a noob to Mac and don't know what else to do. Please let me know if there's a way to add a kill switch to the app. Some sort of a script that could be accessed with a shortcut key that would re-enable the main screen? Thanks

**Comment by Eun** [comment]
Please see Issue #22

**Comment by Sahandyman** [comment]
Dear Eun, As I mentioned in my last comment, I have tried closing the app (using the provided script and another one that force-closes the app) using the shortcut key. The app turns off, but, both screens would remain black. I think, once the monitor is disabled, I must reenable them with the app, otherwise, they would remain disabled, with or without the app being at use.
Meanwhile I have been trying to write a script. I'm a noob and have spent all of yesterday trying to write this, however, it doesn't function properly. It would be a tremendous help if you could take a look at it maybe add to it, so I can use it to re-enable the screens. Thanks again.

![screen shot 2015-05-17 at 8 46 04 pm](https://cloud.githubusercontent.com/assets/12478453/7672975/c846dbb6-fcd5-11e4-875a-3d75e4b404f4.png)
