### ISSUE TITLE
Dell U2212HM problems

### ISSUE THREAD

**Issue by baozilala** [Eun/DisableMonitor#36]
It is not working properly on Dell U2212HM,
When i disable my Dell monitor, dell's wallpaper will come to my main screen(imac 27 2012 mid), sometimes dell's monitor goes blank for few seconds than show up screen again and i have to enable dell monitor and diable again.
So i tried reboot my computer, it worked for few times, after that, it has same problem like i wrote before.
![2015-08-04 4 03 28](https://cloud.githubusercontent.com/assets/774927/9056032/e33f6260-3a5d-11e5-9cfa-37dfbd0244d5.png)
This screen shot can show i disabled my dell monitor, but my monitor stil showing.

>
One thing, 
    i contact my monitor with Mini port to hdmi adapter and hdmi to DVI cable. Will it cause this problem? i bought another adapter, i will try it later, if this caused this problem, i will be back for update.

**Comment by Eun** [comment]
Related to #32
