### ISSUE TITLE
Branch names

### ISSUE THREAD

**Issue by williamboman** [Eun/DisableMonitor#41]
... are a bit confusing. 

The default one is an orphan branch with just a README. The development branch seems to be `gui`? It would be much clearer if the README was moved to the `gui` branch and `gui` renamed to `master`, and `master` set as the default branch on GitHub.

**Comment by Eun** [comment]
Yes the main development branch is `gui`, I will rename it to `master` later.
The reason for the `README` branch is simply that most users are end users and not developers.

**Comment by williamboman** [comment]
You could always make a [GitHub page](https://pages.github.com/) branch for end users. Thanks for the tool btw, it's great :smile:.

**Comment by Eun** [comment]
That is true, but somehow the users always get to this site. And I don't want to confuse them. But thanks for your feedback.
