### ISSUE TITLE
OS X El Capitan does not disable screen

### ISSUE THREAD

**Issue by miceno** [Eun/DisableMonitor#46]
Hi,

Using El Capitan version 10.11 (15A284), if I disable the internal monitor, the screen flashes, and it partially disables the internal monitor, I mean, it disables navigating to it, and System Preferences reports there is just one screen, but the internal monitor screen still shows there.

DisableMonitor version is 1.92.

**Comment by Eun** [comment]
#45

**Comment by miceno** [comment]
Tested again on updated El Capitan 10.11.3 (15D21) and it properly works now on a MacBook Pro (13-inch, Mid 2012).
