### ISSUE TITLE
Support for Widescreen Resolution? (21:9)

### ISSUE THREAD

**Issue by Ruatilda** [Eun/DisableMonitor#61]
Hi!

Thank you for making such a good program.

I wonder if you could add or create an option for 21:9 monitors. 

For example, my monitor supports 2560 x 1080. I have been using mac pixel clock patch, but as I upgraded to Sierra, the patch no longer works. So I tried your program but no luck still..

Let us know!

**Comment by Eun** [comment]
DisableMonitor uses just normal APIs to get the resolutions. It is just a nice "side" feature. I don't think I will put more effort in features that are just nice to have.
Sorry about that...

**Comment by mxrguspxrt** [comment]
Thank you for cool software!

Could you add hardcoded 2560 x 1080 resolution? Both Apple and you have showed weird "careless" for ultra-wide monitors support. Why? :)
