### ISSUE TITLE
support for 3818x1600

### ISSUE THREAD

**Issue by paularmand** [Eun/DisableMonitor#72]
I have a macbook pro early 2015 and would like to connect it to a Dell U3818DW 3840 x 1600. Seems this resolution is not yet supported. Is this an easy fix?

**Comment by Eun** [comment]
Unfortunately there is no way to add resolutions to DisableMonitor, the app uses OSX system calls, and I have no influence on the underlying code.

It might be possible to add resolutions trough a `Displays/Overrides` file.
